# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml

  - repo: local
    hooks:
      - id: run-cypress
        name: run cypress tests
        entry: pnpm cypress:run
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        fail_fast: true
# hooks:
#   - id: go-unit-tests
#     name: run go test s(go test)
#     language: system
#     entry: go test -v ./...
#     pass_filenames: false
#     types: [go]
#     stages: [pre-commit]
